use_frameworks!
source 'http://gitlab.yintech.net/ytx-ios/ytx-pod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'
target 'QXKit_Example' do
  pod 'QXKit', :path => '../'
  pod 'FTRSTestStaticSwift'
  target 'QXKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
#    pod 'Nimble', '~> 7.0.2'
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
